### ISSUE TITLE
TokenJar no longer works on burp 2.0.16 beta

### ISSUE THREAD

**Issue by ghost** [DanNegrea/TokenJar#10]
TokenJar no longer works on burp 2.0.16 beta
after contacting PortSwigger I was told that It looks like newer versions of Java forbid the null character (U+0000) in preference.

last working tokenjar was with burp 2.0.13 beta

the stack dump on burp 2.0.16 beta is : 

java.lang.NullPointerException
	at tokenJar.DataModel.setValue(DataModel.java:185)
	at burp.BurpExtender.processResponseMessage(BurpExtender.java:138)
	at burp.BurpExtender.processProxyMessage(BurpExtender.java:62)
	at burp.d0q.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.NullPointerException
	at tokenJar.DataModel.setValue(DataModel.java:185)
	at burp.BurpExtender.processResponseMessage(BurpExtender.java:138)
	at burp.BurpExtender.processProxyMessage(BurpExtender.java:62)
	at burp.d0q.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by balakumarmanoharan** [comment]
Is there any work around for this??

**Comment by ghost** [comment]
> Is there any work around for this??

the only workaround I know is to go back to burp 2.0.13beta

**Comment by DanNegrea** [comment]
Hi, Thanks for reporting it. I will try to figure out what is happening. For this version I need a PRO licence to test, which I currently don't have. Once I get a fix, you will need to test it yourself.

**Comment by DanNegrea** [comment]
I believe the problem is caused by the JSengine, which is not properly assigned (DataModel:54).
Please use this debug version [TokenJar.zip](https://github.com/DanNegrea/TokenJar/files/2882051/TokenJar.zip):
1. Download
2. Rename it from .zip to .jar 
3. Manually install (Extender > Add > Select File (first from the top) > select TokenJar.jar)
4. Observe output (Extender > TokenJar 2.0 > Output)
5. Report the messages here

In my case I see (tested with latest Burp Community and  Oracle Java 11.0.2 and openjdk 12):
JSengine <.getEngineByName("JavaScript")>Oracle Nashorn
JSengine <.getEngineByExtension("js")>Oracle Nashorn

**Comment by ghost** [comment]
can you push it to the BApp so it can be verified by PortSwigger?

**Comment by DanNegrea** [comment]
Hi, it is a test version, I would preffer not to push it. It can be tested
also in parallel with the original version by manually installing it as
instructed. Please let me know what results you see!

**Comment by nixguy** [comment]
where is the jar file?

**Comment by ghost** [comment]
it did not work,
the grp[1] grabs everything and not just the value of the token

my regex is 
"token" value="([a-zA-Z0-9]*)"

when testing it grabs everything.
from the following line 
<input type="hidden" name="token" value="P8YJRTSY5WFFTRWBTNGJ06NSLXG6UZMB" />

it will grab: 
"token" value="P8YJRTSY5WFFTRWBTNGJ06NSLXG6UZMB"

I think the issue might be due to the move to JDK 11 from PortSwigger, and the support of non-ASCII characters.

**Comment by DanNegrea** [comment]
Sorry for the late reply.

I don't see any problem with your regex. As soon as I obtain my licence I
will debug further.

Am Mi., 20. März 2019 um 14:30 Uhr schrieb nixguy <notifications@github.com

**Comment by Freakazoidile** [comment]
I had the same issue, happy to report that token jar works just fine in Burps official v2.1 release!

**Comment by DanNegrea** [comment]
Thanks for your message. It is good to learn that it works!
