### ISSUE TITLE
Errors with New Burp Version and Test and Regex match and update not working

### ISSUE THREAD

**Issue by Himself132** [DanNegrea/TokenJar#16]
1. Load the extension and observe no errors
2. Navigate to TokenJar tab on Burp
3. Click to highlight dummy populated line with csrf
4. Click regex
5. Populate with a dummy POST body containing regex
6. Click test and observe lack of extraction for value in dummy request
7. Click Save
8. Close Out
9. Manually add Value to some arbitrary number
10. Set browser to Burp proxy
11. Request an arbitrary website to load and intercept
12. Manual change to match a regex in the dummy TokenJar entry used previously
13. Observe lack of update to value in TokenJar tab
14. Navigate to Extender -> TokenJar -> Errors Tab

This has been reproduced by a co-worker on a separate machine.  One is Win10 Pro 64, another is Win10 Enterprise 64, both are 100% up to date on Burp and Windows as of 3/31/2021 excluding any preview updates.

See error below

`	at burp.BurpExtender.processProxyMessage(BurpExtender.java:62)
	at burp.g6l.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "this.JSengine" is null
	at tokenJar.DataModel.setValue(DataModel.java:185)
	at burp.BurpExtender.processResponseMessage(BurpExtender.java:138)
	at burp.BurpExtender.processProxyMessage(BurpExtender.java:62)
	at burp.g6l.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "this.JSengine" is null
	at tokenJar.DataModel.setValue(DataModel.java:185)
	at burp.BurpExtender.processResponseMessage(BurpExtender.java:138)
	at burp.BurpExtender.processProxyMessage(BurpExtender.java:62)
	at burp.g6l.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "this.JSengine" is null
	at tokenJar.DataModel.setValue(DataModel.java:185)
	at burp.BurpExtender.processResponseMessage(BurpExtender.java:138)
	at burp.BurpExtender.processProxyMessage(BurpExtender.java:62)
	at burp.g6l.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "this.JSengine" is null
	at tokenJar.DataModel.setValue(DataModel.java:185)
	at burp.BurpExtender.processResponseMessage(BurpExtender.java:138)
	at burp.BurpExtender.processProxyMessage(BurpExtender.java:62)
	at burp.g6l.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "this.JSengine" is null
	at tokenJar.DataModel.setValue(DataModel.java:185)
	at burp.BurpExtender.processResponseMessage(BurpExtender.java:138)
	at burp.BurpExtender.processProxyMessage(BurpExtender.java:62)
	at burp.g6l.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "this.JSengine" is null
	at tokenJar.DataModel.setValue(DataModel.java:185)
	at burp.BurpExtender.processResponseMessage(BurpExtender.java:138)
	at burp.BurpExtender.processProxyMessage(BurpExtender.java:62)
	at burp.g6l.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "this.JSengine" is null
	at tokenJar.DataModel.setValue(DataModel.java:185)
	at burp.BurpExtender.processResponseMessage(BurpExtender.java:138)
	at burp.BurpExtender.processProxyMessage(BurpExtender.java:62)
	at burp.g6l.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "this.JSengine" is null
	at tokenJar.DataModel.setValue(DataModel.java:185)
	at burp.BurpExtender.processResponseMessage(BurpExtender.java:138)
	at burp.BurpExtender.processProxyMessage(BurpExtender.java:62)
	at burp.g6l.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "this.JSengine" is null
	at tokenJar.DataModel.setValue(DataModel.java:185)
	at burp.BurpExtender.processResponseMessage(BurpExtender.java:138)
	at burp.BurpExtender.processProxyMessage(BurpExtender.java:62)
	at burp.g6l.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "this.JSengine" is null
	at tokenJar.DataModel.setValue(DataModel.java:185)
	at burp.BurpExtender.processResponseMessage(BurpExtender.java:138)
	at burp.BurpExtender.processProxyMessage(BurpExtender.java:62)
	at burp.g6l.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
`

**Comment by Hipapheralkus** [comment]
I confirm I also can't use TokenJar at the moment (latest Kali + Burp v2021.6).
Same behavior - I wanted to parse number from regexp `versionNo":([0-9]+)` . The response is JSON file `"versionNo":5,"recordSt":""`. However, even testing the regexp doesn't work + here is the exception from Error log:
```
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "this.JSengine" is null
	at tokenJar.DataModel.setValue(DataModel.java:185)
	at burp.BurpExtender.processResponseMessage(BurpExtender.java:138)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:87)
	at burp._j.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "this.JSengine" is null
	at tokenJar.DataModel.setValue(DataModel.java:185)
	at burp.BurpExtender.processResponseMessage(BurpExtender.java:138)
	at burp.BurpExtender.processProxyMessage(BurpExtender.java:62)
	at burp.dcz.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

```

**Comment by Hipapheralkus** [comment]
As a quick fix, I've found that it doesn't work because of Java version. Burp Suite is shipped with JRE 15. If you want to make it work, you can run it on JRE<=14, e.g.:
`~/Downloads/jdk-13/bin/java -jar /opt/BurpSuitePro-2.x/burpsuite_pro.jar
`
It's probably because of Nashorn being deprecated since Java 15: https://github.com/hackvertor/hackvertor/issues/52#issuecomment-856108483

**Comment by Himself132** [comment]
Any updates on this item, using an old version of java kind of makes using other extensions problematic - there are no other extensions that do as good of a job with tokens and Portswigger is definitely not listening to it's users baking it in...

**Comment by DanNegrea** [comment]
I identified the issue and I am working on it. It has to do with my comment on the plugin page "JS Engine (NashornScriptEngine) is set to be deprecated (still available in JRE 13)". I will need to test a new JS engine.

**Comment by Himself132** [comment]
thank you!!

**Comment by DanNegrea** [comment]
It took some time to find an alternative to the deprecated javascript engine. Please have a look at the new release. I will try to push it to the official repo soon. 
https://github.com/DanNegrea/TokenJar/releases/tag/2.2

**Comment by Himself132** [comment]
tested and working on most recent burp release.  REALLY appreciate you fixing this and so does my coworker. we use this on almost every other engagment
